### ISSUE TITLE
No panel shown in multi monitor setup.

### ISSUE THREAD

**Issue by lslvr** [nx-desktop/nx-systemtray-applet#3]
When I use Nomad Desktop on my laptop, I use a secondary display also. Neither the panel or the dock are shown on the secondary display. The desktop works without issue: icons are displayed and menus work as well. Is there a setting that must be configured in order to make them appear on the monitor or is this not currently supported?

**Comment by UriHerrera** [comment]
I think is a Plasma setting that isn't configured. We need to check which one it is.

**Comment by lslvr** [comment]
Yes, I think it is. But latte-dock isn't shown on the monitor. Though I'm not sure whether it is a thing of configuration or an issue.

**Comment by lslvr** [comment]
Already solved.
